name: Node.js CI

on:
  push:
    branches: [ ** ]
  pull_request:
    branches: [ ** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      working-directory: ./agent-hub

    - name: Build project
      run: npx webpack
      working-directory: ./agent-hub
